name: Branchlint
description: Lint your Git branch names using GitHub action.
author: Kornel Dubieniecki
branding:
  icon: arrow-up
  color: gray-dark
inputs:
  allowed:
    description: List of allowed branch names containing strings and/or regular expressions separated by a new line.
    required: true
  errorMessage:
    description: String containing a custom error message.
    required: false
  startAfter:
    description: String containing a date in `YYYY-MM-DD hh:mm:ss` format after which the linting will start.
    required: false
runs:
  using: node16
  main: dist/index.js
